SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME LIKE 'Ella'
   OR NAME LIKE 'Lucy'
   OR NAME LIKE 'Pickle'
   OR NAME LIKE 'Rogan'
   OR NAME LIKE 'Sabrina'
   OR NAME LIKE 'Mitty'
ORDER BY ANIMAL_ID;


SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Ella', 'Lucy', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')
ORDER BY ANIMAL_ID;