SELECT SUB.ANIMAL_ID, SUB.NAME FROM (
    SELECT A.ANIMAL_ID, A.NAME FROM ANIMAL_INS A, ANIMAL_OUTS B
    WHERE A.ANIMAL_ID = B.ANIMAL_ID
    AND B.DATETIME IS NOT NULL
    ORDER BY B.DATETIME - A.DATETIME DESC) SUB
WHERE ROWNUM <= 2;